<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <AssemblyTitle>IvaScanner</AssemblyTitle>
    <AssemblyDescription>Card scanner for IVA payment system</AssemblyDescription>
    <Copyright>Copyright © 2024</Copyright>
  </PropertyGroup>



</Project>